### ISSUE TITLE
Do you support local files open?

### ISSUE THREAD

**Issue by qwerqwermhc** [TeamHive/stencil-pdf-viewer#11]
Support for local files to open files like path: file:///D:/pdftest/HGH-18123.pdf
Support for local files to open files like path: file:///D:/pdftest/HGH-18123.pdf
  Is there any ionic3 integration support? I see ng2-pdf-viewer support but does not support the opening of local file files.

**Comment by qwerqwermhc** [comment]
Can the document be more comprehensive? I looked at it and it was ugly. ng2-pdf-viewer The documentation for this plugin is quite comprehensive.

**Comment by sean-perkins** [comment]
Yes this plugin supports local files. We use it in Ionic 4 with Capacitor without problems. You need to replace the `file://` reference for the local address the app is running in the webview on. 

It's a stencil component (web component). It doesn't matter if it's Ionic 1, 2, 3, 4, AngularJS, Angular 2-6, ReactJS, Vue.JS, etc.; it all works the same.

& the README is focused for top-level information to get up and running. Submit a PR if you have additional verbiage that you think would be useful.
