### ISSUE TITLE
He is good on the browser When I run to my phone, he will report the following error.

### ISSUE THREAD

**Issue by qwerqwermhc** [TeamHive/stencil-pdf-viewer#21]
![default](https://user-images.githubusercontent.com/15810962/49335887-92b58480-f631-11e8-993a-0f59f2f866b4.gif)
He is good on the browser
When I run to my phone, he will report the following error.
Unable to open asset URL: file:///android_asset/www/assets/fonts/roboto-bold.woff2
 Unable to open asset URL: file:///android_asset/www/assets/fonts/roboto-bold.woff
Unable to open asset URL: file:///android_asset/www/assets/fonts/roboto-bold.ttf
Why is this so?
@natenorm @jpinkster @db3dev @sean-perkins @sbannigan

**Comment by sean-perkins** [comment]
Not an issue with the plugin. Your PDF is probably referencing a font that's not available on Android devices. I don't own an Android device and pray I'm never kidnapped and forced to use one.

**Comment by qwerqwermhc** [comment]
My Android version is 5.1.2
Is it related to the Android version? Still not supporting Android.
I can open it in the browser. I can't get it on my Android phone. Is this plugin not supporting Android or what is the reason? What time are you testing Android?

**Comment by qwerqwermhc** [comment]
I am very sorry, just that the error is my other error. The real error is here.
TypeError: Cannot read property 'querySelector' of null
TypeError: Cannot read property 'querySelector' of null", source: file:///android_asset/www/build/main.js (178931)

**Comment by qwerqwermhc** [comment]
@sean-perkins
